/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jgenfit.events;

/**
 *
 * @author alex
 */
public enum GenfitEventType {
    GENERAL_SAVE,
    SINGLE_EXPERIMENT_SAVE,
    WEIGHT_PARAMETERS_SAVE,
    OTHER,
    SCATTERING_PARAMETERS_SAVE,
    ADD_NEW_EXPERIMENT_MODEL,
    PARAMETER_SAVE,
    SAVE_EXPERIMENT_MODEL,
    OUTPUT_FOLDER_SELECTED,
    GENFIT_FOLDER_SELECTED, GENFIT_FOURIER_SELECTED, GENFIT_PARAMETER_SELECTED, GENFIT_HOME_SELECTED, SCATERING_FILE_SELECTED, OK, GENFIT_OUTPUTFOLDER_SELECTED, GNUPLOT_APP_SELECTED}
