/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OpenJDialog.java
 *
 * Created on Nov 27, 2011, 8:28:47 PM
 */
package jgenfit;

import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import jgenfit.bussines.GenfitController;
import jgenfit.bussines.GenfitFile;
import jgenfit.utils.GenfitLogger;
import utils.GenfitPropertiesReader;

/**
 *
 * @author alex
 */
public class SaveJDialog extends javax.swing.JDialog {

    GenfitController genfitController;
    private JGenfitView genfitView;
    /** Creates new form OpenJDialog */
    public SaveJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser1.setName("jFileChooser1"); // NOI18N
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jFileChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jFileChooser1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
public void setGenfitFileController(GenfitController genfitController){
    this.genfitController = genfitController;
}

public void setFilePath(String path){
    this.jFileChooser1.setSelectedFile(new File(path));
}

private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

    if (!evt.getActionCommand().equals("CancelSelection")){
    /*    System.err.println("Cancel");
    }
    else{*/
        if (this.jFileChooser1.getSelectedFile() != null){
               // File file = this.jFileChooser1.getSelectedFile();
                if (true){
                    if (this.genfitController != null){
                        //this.genfitController.setGenfitFile(new GenfitFile(this.jFileChooser1.getSelectedFile().getAbsolutePath()));
                        try {
                            if ((this.jFileChooser1.getSelectedFile().getName().length() == 11) && (this.jFileChooser1.getSelectedFile().getName().startsWith("gen") && this.jFileChooser1.getSelectedFile().getName().endsWith(".dat"))){
                                this.genfitController.save(this.jFileChooser1.getSelectedFile().getAbsolutePath());                           
                                GenfitPropertiesReader.setLastOpenedFile(this.jFileChooser1.getSelectedFile().getAbsolutePath());
                                
                                if (this.genfitView != null){
                                    this.genfitView.setStatusBarLabel("File saved " + this.jFileChooser1.getSelectedFile().getAbsolutePath());
                                }
                            }
                            else{                                
                                JOptionPane.showMessageDialog(null,
                                    "File name is not correct. It should be named as genXXXX.dat where XXXX is the run number",
                                    "Warning",
                                    JOptionPane.WARNING_MESSAGE);
                                return;                            
                            }
                        } catch (Exception ex) {
                            Logger.getLogger(SaveJDialog.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    else{
                         GenfitLogger.error("Controller is null");
                    }
                }
                else{
                    GenfitLogger.error("File no readable");
                }            
        }
        else{
            GenfitLogger.error("Selected file: null");
        }       
    }
    this.setVisible(false);
    
    
}//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SaveJDialog dialog = new SaveJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

    void setGenfitView(JGenfitView aThis) {
        this.genfitView = aThis;
    }
}
