/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jgenfit.bussines;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.StringWriter;
import jgenfit.bussines.experiment.GeneralSection;
import jgenfit.bussines.experiment.GenfitModel;
import jgenfit.bussines.experiment.ModelList;
import jgenfit.bussines.experiment.SingleExperimentSection;
import jgenfit.bussines.experiment.ModelSingleExperiment;
import jgenfit.bussines.experiment.Parameter;
import jgenfit.bussines.experiment.SingleExperiment;

/**
 *
 * @author alex
 */
public class GenfitController {
    private GenfitFile genfitFile;

    private String headerSection;
    private String modelList;
    private String experimentalSection;
    
    /**
     * @return the genfitFile
     */
    public GenfitFile getGenfitFile() {
        return genfitFile;
    }

    /**
     * @param genfitFile the genfitFile to set
     */
    public void setGenfitFile(GenfitFile genfitFile) {
        this.genfitFile = genfitFile;    
        this.headerSection = this.genfitFile.getHeaderSection();
        this.modelList = this.genfitFile.getModelListText();
        this.experimentalSection = this.genfitFile.getExperimentalSectionText();
        
        //System.out.println(this.experimentalSection);
    }
    
    public SingleExperimentSection getSingleExperimentSection() {   
        //System.out.println(this.experimentalSection);
        return new SingleExperimentSection(this.experimentalSection);
        //return new SingleExperimentSection(this.genfitFile.getExperimentalSectionText());
    }
    
    public ModelList getModelList(){
        return new ModelList(this.modelList);
        //return new ModelList(this.genfitFile.getModelListText());
    }
    
    public GeneralSection getGeneralSection(){
        return new GeneralSection(this.headerSection);
    }
    
    public void removeExperimentModel(int singleExperiment, int model){
        SingleExperimentSection experiment = this.getSingleExperimentSection();
        SingleExperiment experimentModel = experiment.getExperiments().get(singleExperiment);
        String aux = experimentModel.getContent();
        experimentModel.removeModel(model);
        this.experimentalSection = this.experimentalSection.replace(aux, experimentModel.getContent());
    }
    
     public void addExperimentModel(int singleExperiment){
       SingleExperimentSection experiment = this.getSingleExperimentSection();
       SingleExperiment experimentModel = experiment.getExperiments().get(singleExperiment);
      // System.out.println(experimentModel.getContent());
       
    }
    
    public void save(int singleExperiment, int modelSingleExperimentIndex, ModelSingleExperiment model){
        SingleExperimentSection experiment = this.getSingleExperimentSection();
        SingleExperiment experimentModel = experiment.getExperiments().get(singleExperiment);
        String aux = experimentModel.getContent();
         
        experimentModel.saveModelSingleExperiment(modelSingleExperimentIndex, model);
        this.experimentalSection = this.experimentalSection.replace(aux, experimentModel.getContent());
    }
    
    public void save(int modelIndex, GenfitModel model){
        GenfitModel modelOld = this.getModelList().getModel(modelIndex);
        this.modelList = this.modelList.replace(modelOld.getContent(), model.getContent());
    
    }
    
    public void save(Parameter parameter, int modelIndex, int submodelIndex){
        GenfitModel model = this.getModelList().getModel(modelIndex);
        
           
        String modelContent = model.getContent().replace(model.getSubmodel(submodelIndex).toString(), parameter.toString());
     
        
        this.modelList = this.modelList.replace(model.toString(), modelContent);
        
    }
    
    public void save(GeneralSection generalSection){       
        this.headerSection = generalSection.getContent();        
    }
    
    public void save(SingleExperiment singleExperiment){       
        this.experimentalSection = this.getSingleExperimentSection().getContent().replace(this.getSingleExperimentSection().getExperiments().get(0).getContent(), singleExperiment.getContent());        
    }
    
    public void save(String filePath) throws Exception{
        File file = new File(filePath);
        StringBuilder br = new StringBuilder();    
        br.append("** File generated by JGenfit **\n\n");
        br.append(this.headerSection);
        br.append(this.experimentalSection);
        br.append(this.modelList);
        try{
            FileWriter fw = new FileWriter(file);
            BufferedWriter out = new BufferedWriter(fw);
            out.write(br.toString());
            out.close();
        }
        catch(Exception exp){
            System.err.println(exp.getMessage());
        }       
    }

    
}
