/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeneralJDialog.java
 *
 * Created on Dec 17, 2011, 4:30:29 PM
 */
package jgenfit.general;

import java.awt.event.ActionListener;
import jgenfit.bussines.experiment.GeneralSection;
import jgenfit.events.GenfitEvent;
import jgenfit.events.GenfitEventType;

/**
 *
 * @author alex
 */
public class GeneralJDialog extends javax.swing.JDialog  {
    public GeneralSection generalSection;
    public GenfitEvent genfitEvent;

    /** Creates new form GeneralJDialog */
    public GeneralJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.genfitEvent = new GenfitEvent(this, GenfitEventType.GENERAL_SAVE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldOutputPrefixName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaximumMonkey = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumberOfCyclesForSymann = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldStartingTemperatureOfSimann = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldMaximimZXMINIterationsNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMaximumSimplexIterationsNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNumberOfSubrunForSIMAN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldFinalTemperatureForSymann = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldIterationsNumberForErrorAnalysis = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jCheckBoxSIMANN = new javax.swing.JCheckBox();
        jCheckBoxSimplex = new javax.swing.JCheckBox();
        jCheckBoxZXMIN = new javax.swing.JCheckBox();
        jCheckBoxMONKEY = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jgenfit.JGenfitApp.class).getContext().getResourceMap(GeneralJDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(jLabel1.getFont().deriveFont((float)10));
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextFieldDescription.setFont(jTextFieldDescription.getFont().deriveFont((float)10));
        jTextFieldDescription.setText(resourceMap.getString("jTextFieldDescription.text")); // NOI18N
        jTextFieldDescription.setName("jTextFieldDescription"); // NOI18N

        jLabel2.setFont(jLabel2.getFont().deriveFont((float)10));
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextFieldOutputPrefixName.setEditable(false);
        jTextFieldOutputPrefixName.setFont(jTextFieldOutputPrefixName.getFont().deriveFont((float)10));
        jTextFieldOutputPrefixName.setText(resourceMap.getString("jTextFieldOutputPrefixName.text")); // NOI18N
        jTextFieldOutputPrefixName.setEnabled(false);
        jTextFieldOutputPrefixName.setMaximumSize(new java.awt.Dimension(100, 25));
        jTextFieldOutputPrefixName.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldOutputPrefixName.setName("jTextFieldOutputPrefixName"); // NOI18N

        jLabel3.setFont(jLabel3.getFont().deriveFont((float)10));
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jTextFieldMaximumMonkey.setFont(jTextFieldMaximumMonkey.getFont().deriveFont((float)10));
        jTextFieldMaximumMonkey.setText(resourceMap.getString("jTextFieldMaximumMonkey.text")); // NOI18N
        jTextFieldMaximumMonkey.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jTextFieldMaximumMonkey.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldMaximumMonkey.setName("jTextFieldMaximumMonkey"); // NOI18N

        jLabel4.setFont(jLabel4.getFont().deriveFont((float)10));
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jTextFieldNumberOfCyclesForSymann.setFont(jTextFieldNumberOfCyclesForSymann.getFont().deriveFont((float)10));
        jTextFieldNumberOfCyclesForSymann.setText(resourceMap.getString("jTextFieldNumberOfCyclesForSymann.text")); // NOI18N
        jTextFieldNumberOfCyclesForSymann.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jTextFieldNumberOfCyclesForSymann.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldNumberOfCyclesForSymann.setName("jTextFieldNumberOfCyclesForSymann"); // NOI18N

        jLabel5.setFont(jLabel5.getFont().deriveFont((float)10));
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextFieldStartingTemperatureOfSimann.setFont(jTextFieldStartingTemperatureOfSimann.getFont().deriveFont((float)10));
        jTextFieldStartingTemperatureOfSimann.setText(resourceMap.getString("jTextFieldStartingTemperatureOfSimann.text")); // NOI18N
        jTextFieldStartingTemperatureOfSimann.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jTextFieldStartingTemperatureOfSimann.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldStartingTemperatureOfSimann.setName("jTextFieldStartingTemperatureOfSimann"); // NOI18N

        jLabel6.setFont(jLabel6.getFont().deriveFont((float)10));
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jTextFieldMaximimZXMINIterationsNumber.setFont(jTextFieldMaximimZXMINIterationsNumber.getFont().deriveFont((float)10));
        jTextFieldMaximimZXMINIterationsNumber.setText(resourceMap.getString("jTextFieldMaximimZXMINIterationsNumber.text")); // NOI18N
        jTextFieldMaximimZXMINIterationsNumber.setMaximumSize(new java.awt.Dimension(100, 2147483647));
        jTextFieldMaximimZXMINIterationsNumber.setMinimumSize(new java.awt.Dimension(100, 25));
        jTextFieldMaximimZXMINIterationsNumber.setName("jTextFieldMaximimZXMINIterationsNumber"); // NOI18N

        jLabel7.setFont(jLabel7.getFont().deriveFont((float)10));
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jTextFieldMaximumSimplexIterationsNumber.setFont(jTextFieldMaximumSimplexIterationsNumber.getFont().deriveFont((float)10));
        jTextFieldMaximumSimplexIterationsNumber.setText(resourceMap.getString("jTextFieldMaximumSimplexIterationsNumber.text")); // NOI18N
        jTextFieldMaximumSimplexIterationsNumber.setMaximumSize(new java.awt.Dimension(125, 2147483647));
        jTextFieldMaximumSimplexIterationsNumber.setMinimumSize(new java.awt.Dimension(125, 25));
        jTextFieldMaximumSimplexIterationsNumber.setName("jTextFieldMaximumSimplexIterationsNumber"); // NOI18N

        jLabel8.setFont(jLabel8.getFont().deriveFont((float)10));
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jTextFieldNumberOfSubrunForSIMAN.setFont(jTextFieldNumberOfSubrunForSIMAN.getFont().deriveFont((float)10));
        jTextFieldNumberOfSubrunForSIMAN.setText(resourceMap.getString("jTextFieldNumberOfSubrunForSIMAN.text")); // NOI18N
        jTextFieldNumberOfSubrunForSIMAN.setMaximumSize(new java.awt.Dimension(125, 2147483647));
        jTextFieldNumberOfSubrunForSIMAN.setMinimumSize(new java.awt.Dimension(125, 25));
        jTextFieldNumberOfSubrunForSIMAN.setName("jTextFieldNumberOfSubrunForSIMAN"); // NOI18N

        jLabel9.setFont(jLabel9.getFont().deriveFont((float)10));
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jTextFieldFinalTemperatureForSymann.setFont(jTextFieldFinalTemperatureForSymann.getFont().deriveFont((float)10));
        jTextFieldFinalTemperatureForSymann.setText(resourceMap.getString("jTextFieldFinalTemperatureForSymann.text")); // NOI18N
        jTextFieldFinalTemperatureForSymann.setMaximumSize(new java.awt.Dimension(125, 2147483647));
        jTextFieldFinalTemperatureForSymann.setMinimumSize(new java.awt.Dimension(125, 25));
        jTextFieldFinalTemperatureForSymann.setName("jTextFieldFinalTemperatureForSymann"); // NOI18N

        jLabel10.setFont(jLabel10.getFont().deriveFont((float)10));
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jTextFieldIterationsNumberForErrorAnalysis.setFont(jTextFieldIterationsNumberForErrorAnalysis.getFont().deriveFont((float)10));
        jTextFieldIterationsNumberForErrorAnalysis.setText(resourceMap.getString("jTextFieldIterationsNumberForErrorAnalysis.text")); // NOI18N
        jTextFieldIterationsNumberForErrorAnalysis.setMaximumSize(new java.awt.Dimension(125, 2147483647));
        jTextFieldIterationsNumberForErrorAnalysis.setMinimumSize(new java.awt.Dimension(125, 25));
        jTextFieldIterationsNumberForErrorAnalysis.setName("jTextFieldIterationsNumberForErrorAnalysis"); // NOI18N

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel2.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel2.border.titleFont"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jCheckBoxSIMANN.setBackground(resourceMap.getColor("jCheckBoxSIMANN.background")); // NOI18N
        jCheckBoxSIMANN.setFont(jCheckBoxSIMANN.getFont().deriveFont((float)10));
        jCheckBoxSIMANN.setText(resourceMap.getString("jCheckBoxSIMANN.text")); // NOI18N
        jCheckBoxSIMANN.setName("jCheckBoxSIMANN"); // NOI18N

        jCheckBoxSimplex.setBackground(resourceMap.getColor("jCheckBoxSIMANN.background")); // NOI18N
        jCheckBoxSimplex.setFont(jCheckBoxSimplex.getFont().deriveFont((float)10));
        jCheckBoxSimplex.setText(resourceMap.getString("jCheckBoxSimplex.text")); // NOI18N
        jCheckBoxSimplex.setName("jCheckBoxSimplex"); // NOI18N

        jCheckBoxZXMIN.setBackground(resourceMap.getColor("jCheckBoxSIMANN.background")); // NOI18N
        jCheckBoxZXMIN.setFont(jCheckBoxZXMIN.getFont().deriveFont((float)10));
        jCheckBoxZXMIN.setText(resourceMap.getString("jCheckBoxZXMIN.text")); // NOI18N
        jCheckBoxZXMIN.setName("jCheckBoxZXMIN"); // NOI18N

        jCheckBoxMONKEY.setBackground(resourceMap.getColor("jCheckBoxSIMANN.background")); // NOI18N
        jCheckBoxMONKEY.setFont(jCheckBoxMONKEY.getFont().deriveFont((float)10));
        jCheckBoxMONKEY.setText(resourceMap.getString("jCheckBoxMONKEY.text")); // NOI18N
        jCheckBoxMONKEY.setName("jCheckBoxMONKEY"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(jCheckBoxSIMANN)
                .add(129, 129, 129)
                .add(jCheckBoxSimplex)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 71, Short.MAX_VALUE)
                .add(jCheckBoxZXMIN)
                .add(56, 56, 56)
                .add(jCheckBoxMONKEY)
                .add(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBoxSIMANN)
                    .add(jCheckBoxSimplex)
                    .add(jCheckBoxMONKEY)
                    .add(jCheckBoxZXMIN))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextFieldDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextFieldOutputPrefixName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(21, 21, 21))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel3)
                                    .add(jLabel4)
                                    .add(jLabel6)
                                    .add(jLabel5))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextFieldMaximumMonkey, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .add(jTextFieldMaximimZXMINIterationsNumber, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .add(jTextFieldStartingTemperatureOfSimann, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .add(jTextFieldNumberOfCyclesForSymann, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7)
                                    .add(jLabel10)
                                    .add(jLabel9)
                                    .add(jLabel8))
                                .add(18, 18, 18)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextFieldNumberOfSubrunForSIMAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextFieldMaximumSimplexIterationsNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextFieldIterationsNumberForErrorAnalysis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextFieldFinalTemperatureForSymann, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(47, 47, 47))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextFieldDescription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextFieldOutputPrefixName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel7)
                            .add(jTextFieldMaximumSimplexIterationsNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jTextFieldNumberOfSubrunForSIMAN, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextFieldFinalTemperatureForSymann, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextFieldIterationsNumberForErrorAnalysis, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jTextFieldMaximumMonkey, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextFieldNumberOfCyclesForSymann, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextFieldStartingTemperatureOfSimann, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5)
                            .add(jLabel9))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextFieldMaximimZXMINIterationsNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel6)
                            .add(jLabel10))))
                .add(18, 18, 18)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jButton2))
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    this.generalSection.setValue("General Description", this.jTextFieldDescription.getText());
    
    //set to empty always
    this.generalSection.setValue("Output Prefix", "");
    
    this.generalSection.setValue("Maximum MONKEY", this.jTextFieldMaximumMonkey.getText());
    this.generalSection.setValue("Number of Cycles for SIMANN", this.jTextFieldNumberOfCyclesForSymann.getText());
    this.generalSection.setValue("Starting Temperature", this.jTextFieldStartingTemperatureOfSimann.getText());
    this.generalSection.setValue("Maximum ZXMIN", this.jTextFieldMaximimZXMINIterationsNumber.getText());
    
    
    this.generalSection.setValue("Maximum SIMPLEX", this.jTextFieldMaximumSimplexIterationsNumber.getText());
    this.generalSection.setValue("Number of Subrun for SIMANN", this.jTextFieldNumberOfSubrunForSIMAN.getText());
    this.generalSection.setValue("Final Temperature for", this.jTextFieldFinalTemperatureForSymann.getText());
    this.generalSection.setValue("Iterations number for error analysis", this.jTextFieldIterationsNumberForErrorAnalysis.getText());
    
    if (this.jCheckBoxMONKEY.isSelected()){
        this.generalSection.setValue("MONKEY  minimization flag", "1");
    }
    else{
        this.generalSection.setValue("MONKEY  minimization flag", "0");
    }
    
    if (this.jCheckBoxSIMANN.isSelected()){
        this.generalSection.setValue("SIMANN  minimization flag", "1");
    }
    else{
        this.generalSection.setValue("SIMANN  minimization flag", "0");
    }
    
     if (this.jCheckBoxSimplex.isSelected()){
        this.generalSection.setValue("SIMPLEX minimization flag", "1");
    }
    else{
        this.generalSection.setValue("SIMPLEX minimization flag", "0");
    }
     
    if (this.jCheckBoxZXMIN.isSelected()){
        this.generalSection.setValue("ZXMIN   minimization flag", "1");
    }
    else{
        this.generalSection.setValue("ZXMIN   minimization flag", "0");
    }
    
    this.genfitEvent.fire();
    
    this.setVisible(false);
    
    /*
     *  if(generalSection.getValue("MONKEY  minimization flag").trim().equals("1")){
            this.jCheckBoxMONKEY.setSelected(true);
        }else{
           this.jCheckBoxMONKEY.setSelected(false);
        }
        
        if(generalSection.getValue("SIMANN  minimization flag").trim().equals("1")){
            this.jCheckBoxSIMANN.setSelected(true);
        }else{
           this.jCheckBoxSIMANN.setSelected(false);
        }
        
        if(generalSection.getValue("SIMPLEX  minimization flag").trim().equals("1")){
            this.jCheckBoxSimplex.setSelected(true);
        }else{
            this.jCheckBoxSimplex.setSelected(false);
        }
        
        if(generalSection.getValue("ZXMIN  minimization flag").trim().equals("1")){
            this.jCheckBoxZXMIN.setSelected(true);
    
        this.jTextFieldMaximumSimplexIterationsNumber.setText(generalSection.getValue("Maximum SIMPLEX"));
        this.jTextFieldNumberOfSubrunForSIMAN.setText(generalSection.getValue("Number of Subrun for SIMANN "));
        this.jTextFieldFinalTemperatureForSymann.setText(generalSection.getValue("Final Temperature for"));
        this.jTextFieldIterationsNumberForErrorAnalysis.setText(generalSection.getValue("Iterations number for error analysis"));
        */
    
            
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                GeneralJDialog dialog = new GeneralJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void setGeneralSection(GeneralSection generalSection){
        this.generalSection = generalSection;
      
        
        this.jTextFieldDescription.setText(generalSection.getValue("General Description"));
        this.jTextFieldOutputPrefixName.setText("");
        
        this.jTextFieldMaximumMonkey.setText(generalSection.getValue("Maximum MONKEY"));
        this.jTextFieldNumberOfCyclesForSymann.setText(generalSection.getValue("Number of Cycles for SIMANN"));
        this.jTextFieldStartingTemperatureOfSimann.setText(generalSection.getValue("Starting Temperature"));
        this.jTextFieldMaximimZXMINIterationsNumber.setText(generalSection.getValue("Maximum ZXMIN"));
        
        this.jTextFieldMaximumSimplexIterationsNumber.setText(generalSection.getValue("Maximum SIMPLEX"));
        this.jTextFieldNumberOfSubrunForSIMAN.setText(generalSection.getValue("Number of Subrun for SIMANN "));
        this.jTextFieldFinalTemperatureForSymann.setText(generalSection.getValue("Final Temperature for"));
        this.jTextFieldIterationsNumberForErrorAnalysis.setText(generalSection.getValue("Iterations number for error analysis"));
        
        if(generalSection.getValue("MONKEY  minimization flag").trim().equals("1")){
            this.jCheckBoxMONKEY.setSelected(true);
        }else{
           this.jCheckBoxMONKEY.setSelected(false);
        }
        
        if(generalSection.getValue("SIMANN  minimization flag").trim().equals("1")){
            this.jCheckBoxSIMANN.setSelected(true);
        }else{
           this.jCheckBoxSIMANN.setSelected(false);
        }
        
        if(generalSection.getValue("SIMPLEX minimization flag").trim().equals("1")){
            this.jCheckBoxSimplex.setSelected(true);
        }else{
            this.jCheckBoxSimplex.setSelected(false);
        }
        
        if(generalSection.getValue("ZXMIN   minimization flag").trim().equals("1")){
            this.jCheckBoxZXMIN.setSelected(true);
        }else{
            this.jCheckBoxZXMIN.setSelected(false);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxMONKEY;
    private javax.swing.JCheckBox jCheckBoxSIMANN;
    private javax.swing.JCheckBox jCheckBoxSimplex;
    private javax.swing.JCheckBox jCheckBoxZXMIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldFinalTemperatureForSymann;
    private javax.swing.JTextField jTextFieldIterationsNumberForErrorAnalysis;
    private javax.swing.JTextField jTextFieldMaximimZXMINIterationsNumber;
    private javax.swing.JTextField jTextFieldMaximumMonkey;
    private javax.swing.JTextField jTextFieldMaximumSimplexIterationsNumber;
    private javax.swing.JTextField jTextFieldNumberOfCyclesForSymann;
    private javax.swing.JTextField jTextFieldNumberOfSubrunForSIMAN;
    private javax.swing.JTextField jTextFieldOutputPrefixName;
    private javax.swing.JTextField jTextFieldStartingTemperatureOfSimann;
    // End of variables declaration//GEN-END:variables
}
